# Paypal donation link
custom: https://www.paypal.com/cgi-bin/webscr?&business=d87d87%40gmail.com&bn=PP-DonationsBF:btn_donateCC_LG.gif:NonHosted&lc=US&item_name=NugAddons&cmd=_donations&rm=1&no_shipping=1&currency_code=USD